# Generated by Django 3.1.2 on 2020-12-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('cover', models.ImageField(upload_to='covers')),
                ('price', models.PositiveIntegerField()),
                ('printed_year', models.PositiveSmallIntegerField()),
                ('authors', models.ManyToManyField(related_name='books', to='books.Author')),
                ('categories', models.ManyToManyField(related_name='books', to='books.Category')),
            ],
        ),
    ]
