# Generated by Django 3.1.2 on 2020-12-18 13:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_mycart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 13, 10, 7, 498317, tzinfo=utc), null=True),
        ),
    ]
