# Generated by Django 3.1.2 on 2020-12-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20201225_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='qrimage',
            field=models.ImageField(blank=True, null=True, upload_to='qrimage'),
        ),
    ]
