# Generated by Django 3.1.2 on 2020-12-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audiofile'),
        ),
    ]
