# Generated by Django 3.1.2 on 2020-12-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20201230_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='invoice',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
