# Generated by Django 2.2.12 on 2021-04-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_orders_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='audio',
        ),
    ]
