# Generated by Django 2.1.5 on 2022-02-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20220224_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='forgot_ans',
            field=models.CharField(default='', max_length=100, verbose_name='Write Something Which Help You To Change Your Password'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=80),
        ),
    ]
